### ISSUE TITLE
b2sdk.exception.InvalidAuthToken: Invalid authorization token.

### ISSUE THREAD

**Issue by harrim4n** [ehossack/django-backblaze-b2#23]
I get an exception when trying to run the docker demo application.

# Steps to reproduce
1. Clone repo
2. `make setup`
3. Create new B2 bucket, default settings (i.e., private bucket)
4. Enter `BACKBLAZE_APPLICATION_KEY_ID`, `BACKBLAZE_APPLICATION_KEY` and `BACKBLAZE_BUCKET` in the `settings.env` file
5. `make run-sample-project`

# Exception

```
Initializing DjangoCacheAccountInfo with cache 'django-backblaze-b2'
Traceback (most recent call last):
  File "//sample_app/manage.py", line 22, in <module>
    main()
  File "//sample_app/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 395, in execute
    django.setup()
  File "/usr/local/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.9/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/usr/local/lib/python3.9/site-packages/django/apps/config.py", line 301, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/sample_app/b2_file_app/models.py", line 6, in <module>
    class ModelWithFiles(models.Model):
  File "/sample_app/b2_file_app/models.py", line 7, in ModelWithFiles
    b2StorageFile = models.FileField(
  File "/usr/local/lib/python3.9/site-packages/django/db/models/fields/files.py", line 235, in __init__
    self.storage = self.storage()
  File "/usr/local/lib/python3.9/site-packages/django_backblaze_b2/storage.py", line 73, in __init__
    self.b2Api
  File "/usr/local/lib/python3.9/site-packages/django_backblaze_b2/storage.py", line 130, in b2Api
    self._b2Api.authorize_account(**self._authInfo)
  File "/usr/local/lib/python3.9/site-packages/logfury/v0_1/trace_call.py", line 84, in wrapper
    return function(*wrapee_args, **wrapee_kwargs)
  File "/usr/local/lib/python3.9/site-packages/b2sdk/api.py", line 164, in authorize_account
    self.session.authorize_account(realm, application_key_id, application_key)
  File "/usr/local/lib/python3.9/site-packages/b2sdk/session.py", line 115, in authorize_account
    if not self.account_info.is_same_account(account_id, realm):
  File "/usr/local/lib/python3.9/site-packages/logfury/v0_1/trace_call.py", line 84, in wrapper
    return function(*wrapee_args, **wrapee_kwargs)
  File "/usr/local/lib/python3.9/site-packages/b2sdk/account_info/abstract.py", line 125, in is_same_account
    return self.get_account_id() == account_id and self.get_realm() == realm
  File "/usr/local/lib/python3.9/site-packages/django_backblaze_b2/cache_account_info.py", line 32, in getter_function
    raise InvalidAuthToken(
b2sdk.exception.InvalidAuthToken: Invalid authorization token. Server said: Token refresh required to determine value of 'account_id' (401)
make: *** [Makefile:115: run-sample-proj] Error 1
```

**Comment by ehossack** [comment]
Hmm. Currently main is an unreleased version of the code so it's possible there are errors. 
I'll run it on my end tomorrow and see if it's the same. 

Good indicator the sample app should be in the test suite.

**Comment by ehossack** [comment]
Confirmed I see the same behaviour, working on a fix.

**Comment by ehossack** [comment]
Should be fixed now, feel free to re-open if it does not work on your end!
